// Generated by 'unplugin-auto-import'
// We suggest you to commit this file into source control
// declare global {
//   interface IStringObject {
//     [index: string]: any
//   }
// }
// export {}
// axios 请求格式自定义
import { AxiosRequestConfig } from "axios";
declare module 'axios'{
  interface AxiosInstance{
    (config:AxiosRequestConfig):Promise<any>
  }
}